
package com.winnovature.dao;


public class ReportsQueries {
	
	public static String TagDetailsReport = "{call pro_GetTagDetails(?,?)}";

	public static String WalletTransactionReport = "SELECT wm.TXN_DATE 'TXN DATE',wm.WALLET_TXN_ID 'TXN ID' ,wm.TXN_TYPE 'TXN TYPE',wm.TXN_AMOUNT 'TXN AMOUNT',wm.WALLET_ID 'WALLET ID',wm1.name 'CUSTOMER NAME',wm1.contact_number 'PHONE NO',wm.PARTNER_REF_NO 'REF NO',wm.UDF1 'TRANSACTION TYPE',wm.UDF2 'GEO CODE',wm.UDF3 'BARCODE',wm.UDF4 'ADDRESS',wm.UDF5 'VEHICLE NO',wm1.pos_id 'POS ID' FROM wallet_txn_info wm inner join tbl_wallet_master wm1 on wm.WALLET_ID=wm1.wallet_id order by wm.TXN_DATE desc limit 40";

	public static String WalletTransactionBYDATE = "SELECT wm.TXN_DATE 'TXN DATE',wm.WALLET_TXN_ID 'TXN ID' ,wm.TXN_TYPE 'TXN TYPE',wm.TXN_AMOUNT 'TXN AMOUNT',wm.WALLET_ID 'WALLET ID',wm1.name 'CUSTOMER NAME',wm1.contact_number 'PHONE NO',wm.PARTNER_REF_NO 'REF NO',wm.UDF1 'TRANSACTION TYPE',wm.UDF2 'GEO CODE',wm.UDF3 'BARCODE',wm.UDF4 'ADDRESS',wm.UDF5 'VEHICLE NO',wm1.pos_id 'POS ID' FROM wallet_txn_info wm inner join tbl_wallet_master wm1 on wm.WALLET_ID=wm1.wallet_id where wm.TXN_DATE Between ? AND ? order by wm.TXN_DATE desc limit 40";
	
	public static String ReconReportBYDATE = "select vtl.customer_id 'Customer_Id',cm.staff_name 'Customer_Name',twm.wallet_id 'Wallet_Id',rpm.tag_id 'Tag_Id', rm.msg_identifier 'Msg_Identifier', rm.txn_timestamp 'Txn_Time',rm.txn_amount, rm.acq_txn_id Acq_Txn_id ,rm.recon_date_time 'Recon_Date' from recon_master rm inner join req_pay_master rpm on rm.Acq_Txn_id=rpm.original_txn_id inner join vehicle_tag_linking vtl on rpm.tag_id=vtl.tag_id inner join tbl_wallet_master twm on vtl.customer_id=twm.user_id inner join customer_master cm on twm.user_id=cm.cust_id where rm.recon_date_time between ? AND ? order by rm.id";

	//public static String InventoryNewReportBYDATE = "SELECT CASE WHEN branch_id = '0' THEN 'HO' ELSE  branch_id END AS  'Branch User ID',count(*) 'Total Count',tag_class_id 'Tag Class', SUM(CASE WHEN status = '4' THEN 1 ELSE 0 END) AS  'Used Tag',SUM(CASE  WHEN  status != '4'  THEN 1 ELSE 0 END) AS 'UnUsed Tag' FROM inventory_master  where date_time between ? AND ? group by branch_id ,tag_class_id";

	//public static String InventoryNewReport = "SELECT CASE WHEN branch_id = '0' THEN 'HO' ELSE  branch_id END AS  'Branch User ID',count(*) 'Total Count',tag_class_id 'Tag Class', SUM(CASE WHEN status = '4' THEN 1 ELSE 0 END) AS  'Used Tag',SUM(CASE  WHEN  status != '4'  THEN 1 ELSE 0 END) AS 'UnUsed Tag' FROM inventory_master group by branch_id ,tag_class_id";

	public static String InventoryNewReportBYDATE = "SELECT CASE WHEN branch_id = '0' THEN 'HO' WHEN agent_id!='0' AND branch_id!='0' THEN agent_id ELSE  branch_id END AS 'Branch User ID',count(*) 'Total Count',tag_class_id 'Tag Class', SUM(CASE WHEN status = '4' THEN 1 ELSE 0 END) AS  'Used Tag',SUM(CASE  WHEN  status != '4'  THEN 1 ELSE 0 END) AS 'UnUsed Tag' FROM inventory_master where date_time between ? AND ? group by branch_id, tag_class_id";
	public static String InventoryNewReport = "SELECT CASE WHEN branch_id = '0' THEN 'HO' WHEN agent_id!='0' AND branch_id!='0' THEN agent_id ELSE  branch_id END AS 'Branch User ID',count(*) 'Total Count',tag_class_id 'Tag Class', SUM(CASE WHEN status = '4' THEN 1 ELSE 0 END) AS  'Used Tag',SUM(CASE  WHEN  status != '4'  THEN 1 ELSE 0 END) AS 'UnUsed Tag' FROM inventory_master group by branch_id, tag_class_id";
	
	//public static String TransactionReport = "select req.id ,req.message_identifier,req.txn_id , req.original_txn_id ,case when req.vehicle_no is null then 'NA' when  req.vehicle_no = '' then 'NA' else req.vehicle_no end 'Vehicle_No',req.txn_amount ,req.txn_time,case when resp.post_status = 1 then 'Response Sent to NPCI' else 'Txn Received from NPCI' end as 'NPCI_Response_Status',case when req.resp_status = 1 then 'Response Received from account/wallet' else 'Not Posted to account/wallet Posting Failed' end as 'Response_Status',resp.npci_resp_code ,req.error_code ,req.acq_id , req.avc, req.txn_type  ,req.toll_plaza_id ,req.toll_plaza_name , req.tag_id ,req.tid  ,req.reader_ts ,req.recon_status , req.exception_code ,req.is_commercial ,'Plaza' as 'Merchant_Type',  req.toll_plaza_type  ,wtxn.WALLET_ID  as 'account_id', wtxn.OPENING_BALANCE as 'opening_bal',wtxn.UDF2 ='0.00' as 'credit_amount',wtxn.TXN_AMOUNT as 'debit_amount', wtxn.closing_balance from req_pay_master req , resp_pay_master resp , wallet_transaction_info wtxn where req.txn_id = resp.req_id and wtxn.partner_ref_no = req.txn_id and wtxn.pay_mode ='TOLLTXN' and wtxn.txn_type ='DEBIT' order by req.id desc limit 200";
	
	//public static String TransactionReportBYDATE = "select req.id ,req.message_identifier,req.txn_id , req.original_txn_id ,case when req.vehicle_no is null then 'NA' when  req.vehicle_no = '' then 'NA' else req.vehicle_no end 'Vehicle_No',req.txn_amount ,req.txn_time,case when resp.post_status = 1 then 'Response Sent to NPCI' else 'Txn Received from NPCI' end as 'NPCI_Response_Status',case when req.resp_status = 1 then 'Response Received from account/wallet' else 'Not Posted to account/wallet Posting Failed' end as 'Response_Status',resp.npci_resp_code ,req.error_code ,req.acq_id , req.avc, req.txn_type  ,req.toll_plaza_id ,req.toll_plaza_name , req.tag_id ,req.tid  ,req.reader_ts ,req.recon_status , req.exception_code ,req.is_commercial ,'Plaza' as 'Merchant_Type',  req.toll_plaza_type  ,wtxn.WALLET_ID  as 'account_id', wtxn.OPENING_BALANCE as 'opening_bal',wtxn.UDF2 ='0.00' as 'credit_amount',wtxn.TXN_AMOUNT as 'debit_amount', wtxn.closing_balance from req_pay_master req , resp_pay_master resp , wallet_transaction_info wtxn where req.txn_id = resp.req_id and wtxn.partner_ref_no = req.txn_id and wtxn.pay_mode ='TOLLTXN' and wtxn.txn_type ='DEBIT' and req.txn_time between ? and ? order by req.id desc limit 200";
	
	public static String TransactionReportCustomer = "select req.id ,req.message_identifier,req.txn_id , req.original_txn_id ,case when req.vehicle_no is null then 'NA' when  req.vehicle_no = '' then 'NA' else req.vehicle_no end 'Vehicle_No',req.txn_amount ,req.txn_time,req.cbs_reference_no , req.cbs_response_date,req.error_code ,req.acq_id , req.avc, req.txn_type  ,req.toll_plaza_id ,req.toll_plaza_name , req.tag_id ,req.tid  ,req.reader_ts ,req.recon_status , req.exception_code ,req.is_commercial ,'Plaza' as 'Merchant_Type',  req.toll_plaza_type from req_pay_master req, vehicle_tag_linking v where v.tag_id=req.tag_id and v.customer_id= ? order by req.id desc limit 200";
	
	public static String TransactionReportBYDATECustomer = "select req.id ,req.message_identifier,req.txn_id , req.original_txn_id ,case when req.vehicle_no is null then 'NA' when  req.vehicle_no = '' then 'NA' else req.vehicle_no end 'Vehicle_No',req.txn_amount ,req.txn_time,req.cbs_reference_no , req.cbs_response_date,req.error_code ,req.acq_id , req.avc, req.txn_type  ,req.toll_plaza_id ,req.toll_plaza_name , req.tag_id ,req.tid  ,req.reader_ts ,req.recon_status , req.exception_code ,req.is_commercial ,'Plaza' as 'Merchant_Type',  req.toll_plaza_type from req_pay_master req, vehicle_tag_linking v where v.tag_id=req.tag_id and v.customer_id= ? and req.txn_time between ? and ? order by req.id desc limit 200";
	
	public static String TransactionReportAdmin = "select req.id ,req.message_identifier,req.txn_id , req.original_txn_id ,case when req.vehicle_no is null then 'NA' when  req.vehicle_no = '' then 'NA' else req.vehicle_no end 'Vehicle_No',req.txn_amount ,req.txn_time,req.cbs_reference_no , req.cbs_response_date,req.error_code ,req.acq_id , req.avc, req.txn_type  ,req.toll_plaza_id ,req.toll_plaza_name , req.tag_id ,req.tid  ,req.reader_ts ,req.recon_status , req.exception_code ,req.is_commercial ,'Plaza' as 'Merchant_Type',  req.toll_plaza_type from req_pay_master req order by req.id desc limit 200";
	
	public static String TransactionReportBYDATEAdmin = "select req.id ,req.message_identifier,req.txn_id , req.original_txn_id ,case when req.vehicle_no is null then 'NA' when  req.vehicle_no = '' then 'NA' else req.vehicle_no end 'Vehicle_No',req.txn_amount ,req.txn_time,req.cbs_reference_no , req.cbs_response_date,req.error_code ,req.acq_id , req.avc, req.txn_type  ,req.toll_plaza_id ,req.toll_plaza_name , req.tag_id ,req.tid  ,req.reader_ts ,req.recon_status , req.exception_code ,req.is_commercial ,'Plaza' as 'Merchant_Type',  req.toll_plaza_type from req_pay_master req where req.txn_time between ? and ? order by req.id desc limit 200";
	
	public static String PuchaseOrderReport="select  distinct pm.id , pm.po_id ,sm.supplier_name ,po.supp_id , pm.tag_class_id ,pm.order_qty , case when im.status = '0' then 'UNPROCESSED' when  im.status = '1' then 'IN TRANSIT' when im.status = '3'  then 'IN STOCK' else 'NA' end as Status,po.total_order_value ,po.created_on ,po.created_by , po.approved_on ,po.approved_by  from po_item_master pm inner join  inventory_master im on pm.po_id = im.po_id inner join po_master po on pm.po_id=po.po_id left join supplier_master sm on po.supp_id=sm.supplier_id where im.status in('0','1','3')  group by pm.id,pm.tag_class_id,pm.order_qty,im.status order by pm.id limit 200;";
	
	public static String PuchaseOrderReportBYDATE="select  distinct pm.id , pm.po_id ,sm.supplier_name ,po.supp_id , pm.tag_class_id ,pm.order_qty , case when im.status = '0' then 'UNPROCESSED' when  im.status = '1' then 'IN TRANSIT' when im.status = '3'  then 'IN STOCK' else 'NA' end as Status,po.total_order_value ,po.created_on ,po.created_by , po.approved_on ,po.approved_by  from po_item_master pm inner join  inventory_master im on pm.po_id = im.po_id inner join po_master po on pm.po_id=po.po_id left join supplier_master sm on po.supp_id=sm.supplier_id where  pm.rodt between ? and ? and im.status in('0','1','3')  group by pm.id,pm.tag_class_id,pm.order_qty,im.status order by pm.id ;";

	public static String VehicleReportBYDATE="select v.customer_id , upper(c.customer_name) as 'Customer_Name' , v.vehicle_number,  v.tag_class_id , v.tid , v.tag_id  ,v.barcode_data , case when  cv.is_commercial ='1' then 'Y' else 'N' end as 'Is_Commercial'   from vehicle_tag_linking v, customer_info c , customer_vehicle_info cv  where c.user_id=v.customer_id and v.vehicle_number = cv.vehicle_number and v.customer_id = cv.user_id  and v.vehicle_id is not null and v.vehicle_number is not null and v.customer_id is not null and v.rodt between ? and ?";

	public static String VehicleReport="select v.customer_id , upper(c.customer_name) as 'Customer_Name' , v.vehicle_number,  v.tag_class_id , v.tid , v.tag_id  ,v.barcode_data , case when  cv.is_commercial ='1' then 'Y' else 'N' end as 'Is_Commercial'   from vehicle_tag_linking v, customer_info c , customer_vehicle_info cv  where c.user_id=v.customer_id and v.vehicle_number = cv.vehicle_number and v.customer_id = cv.user_id  and v.vehicle_id is not null and v.vehicle_number is not null and v.customer_id is not null";

	public static String CustomerReport="SELECT cm.user_id ,wm.wallet_id,UPPER(cm.customer_name) as 'Customer_Name',cm.email_id,cm.contact_number ,CONCAT(am.resi_address1,' , ', am.resi_address2,', ',am.resi_city,', ',am.resi_pin) as 'Address', am.resi_state ,acm.account_number ,acm.bank_name , acm.account_type, cm.is_wallet ,wm.current_balance,wm.sec_deposit,cm.created_by ,cm.created_on,cm.approved_by ,cm.approved_on,cm.modified_by ,cm.created_on, cm.status, wm.max_balance,wm.valid_upto FROM customer_info cm INNER JOIN address_info am on cm.user_id=am.user_id INNER JOIN account_info acm on cm.user_id=acm.user_id INNER JOIN customer_kyc_info ckm on ckm.user_id=cm.user_id left join wallet_info wm on cm.wallet_id = wm.wallet_id order by cm.created_on desc limit 50";

	public static String CustomerReportBYDATE="SELECT cm.user_id ,wm.wallet_id,UPPER(cm.customer_name) as 'Customer_Name',cm.email_id,cm.contact_number ,CONCAT(am.resi_address1,' , ', am.resi_address2,', ',am.resi_city,', ',am.resi_pin) as 'Address', am.resi_state ,acm.account_number ,acm.bank_name , acm.account_type, cm.is_wallet ,wm.current_balance,wm.sec_deposit,cm.created_by ,cm.created_on,cm.approved_by ,cm.approved_on,cm.modified_by ,cm.created_on, cm.status, wm.max_balance,wm.valid_upto FROM customer_info cm INNER JOIN address_info am on cm.user_id=am.user_id INNER JOIN account_info acm on cm.user_id=acm.user_id INNER JOIN customer_kyc_info ckm on ckm.user_id=cm.user_id left join wallet_info wm on cm.wallet_id = wm.wallet_id and cm.created_on between ? and ? order by cm.created_on desc limit 50";

	public static String CustomerVehicleDetails="select cm.vehicle_number ,cm.tag_class_id ,cm.engine_number ,cm.chassis_number, case when vt.tag_id is null then 'NA' else vt.tag_id end as TagID, case when vt.barcode_data is null then 'NA' else vt.barcode_data end as BarCode from customer_vehicle_master cm left join vehicle_tag_linking vt on cm.vehicle_number = vt.vehicle_number where cm.cust_id= ?;";

	public static String CustomerAuditDetails="select cm.staff_name ,cme.staff_name ,cm.email_id ,cme.email_id  ,cm.contact_number  ,cme.contact_number ,am.resi_add1  ,ame.resi_add1 ,am.resi_address2 ,ame.resi_address2 ,am.resi_pin ,ame.resi_pin,am.resi_city ,ame.resi_city ,am.resi_state ,ame.resi_state ,cm.isModifiedby  from customer_master_edit_old cme inner join address_master_edit_old ame on cme.cust_id=ame.user_id inner join  customer_master cm on cme.cust_id=cm.cust_id inner join address_master am on cm.cust_id=am.user_id where cme.cust_id= ? limit 5;";

	public static String InventoryReport="SELECT DISTINCT tag_class_id from inventory_master where status = 3";
	
	public static String InventoryReportPRO = "{call pro_InventoryDetails(?,?,?,?)}";
	
	public static String InventoryReportPro2 = "{call pro_GetAvailableInventoryViewMoreDetails(?,?)}";
	
	
	public static String WalletTxnReport = "SELECT * from wallet_transaction_info order by txn_date limit 50";
	
	public static String WalletTxnReportByDate = "SELECT * from wallet_transaction_info WHERE txn_date between ? and ? order by txn_date limit 200";
	
	public static String CustWalletTxnReport = "SELECT * from wallet_transaction_info WHERE wallet_id=? order by txn_date limit 50";
	
	public static String CustWalletTxnReportByDate = "SELECT * from wallet_transaction_info WHERE txn_date between ? and ? and wallet_id=? order by txn_date limit 200";
	
	public static String CustVehicleReportBYDATE="select v.customer_id , upper(c.customer_name) as 'Customer_Name' , v.vehicle_number,  v.tag_class_id , v.tid , v.tag_id  ,v.barcode_data , case when  cv.is_commercial ='1' then 'Y' else 'N' end as 'Is_Commercial'   from vehicle_tag_linking v, customer_info c , customer_vehicle_info cv  where c.user_id=v.customer_id and v.vehicle_number = cv.vehicle_number and v.customer_id = cv.user_id  and v.vehicle_id is not null and v.vehicle_number is not null and v.customer_id is not null and v.rodt between ? and ? and v.customer_id = ?";

	public static String CustVehicleReport="select v.customer_id , upper(c.customer_name) as 'Customer_Name' , v.vehicle_number,  v.tag_class_id , v.tid , v.tag_id  ,v.barcode_data , case when  cv.is_commercial ='1' then 'Y' else 'N' end as 'Is_Commercial'   from vehicle_tag_linking v, customer_info c , customer_vehicle_info cv  where c.user_id=v.customer_id and v.vehicle_number = cv.vehicle_number and v.customer_id = cv.user_id  and v.vehicle_id is not null and v.vehicle_number is not null and v.customer_id is not null and v.customer_id = ?";

	public static String ExceptionReport="select vtl.customer_id, vtl.tid,tel.tag_id,vtl.barcode_data,vtl.vehicle_number,tel.exe_code,tel.insertion_flag,vtl.tag_class_id,tel.msg_id,tel.npci_updated_date from tag_exception_list tel join vehicle_tag_linking vtl on tel.tag_id = vtl.tag_id  limit 100";
	
	
	public static String ExceptionReportBYDATE="select vtl.customer_id, vtl.tid,tel.tag_id,vtl.barcode_data,vtl.vehicle_number,tel.exe_code,tel.insertion_flag,vtl.tag_class_id,tel.msg_id,tel.npci_updated_date from tag_exception_list tel inner join vehicle_tag_linking vtl on tel.tag_id = vtl.tag_id and tel.rodt between ? and ? limit 200";


}